# Generated by Django 3.0.6 on 2020-06-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category_Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='')),
                ('category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Category_Auth.Category')),
            ],
        ),
    ]
