# Generated by Django 3.0.6 on 2020-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category_Auth', '0002_auto_20200608_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
