# Generated by Django 3.0.6 on 2020-06-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category_Auth', '0003_auto_20200608_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.URLField(max_length=250)),
                ('category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Category_Auth.Category')),
            ],
        ),
    ]
