# Generated by Django 3.0.6 on 2020-06-13 08:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category_Auth', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('organiser_name', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=300)),
                ('budget', models.IntegerField(default=0)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('dateandtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=500)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('organisereventid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Category_Auth.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTestmonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='')),
                ('testmonial_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Category_Auth.Testmonial')),
            ],
        ),
    ]
